<a href="https://colab.research.google.com/github/mercy-ndolo/data_science/blob/main/Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.datasets import load_iris
import numpy as np
import statsmodels.api as sm

# Load the dataset
iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create and train the logistic regression model
model = LogisticRegression(max_iter=10000, multi_class='multinomial')
model.fit(X_train, y_train)

# Make predictions and evaluate the model
predictions = model.predict(X_test)
print("\nConfusion Matrix:\n", confusion_matrix(y_test, predictions))
print("\nClassification Report:\n", classification_report(y_test, predictions))

# Analyze the coefficients
coefficients = pd.DataFrame(model.coef_, columns=X.columns)
coefficients['intercept'] = model.intercept_
print("\nCoefficients of the model:\n", coefficients)

# If you want p-values and more statistics, use statsmodels
X_train_const = sm.add_constant(X_train) # adding a constant

model_sm = sm.MNLogit(y_train, X_train_const)
result = model_sm.fit()

print(result.summary())


# In[ ]:






Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Coefficients of the model:
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0          -0.404609          0.868456          -2.278007         -0.957490   
1           0.466521         -0.375242          -0.187680         -0.720368   
2          -0.061912         -0.493214           2.465686          1.677858   

   intercept  
0   8.862172  
1   2.209910  
2 -11.072082  
         Current function value: 0.053201
         Iterations: 35
                          MNLogit Regression Results             

/usr/local/lib/python3.10/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
